name: MCPFun
main: me.MCPFun.main.MCPFunMain
version: 0.1
description: Implements a fun gamemode
commands:
  AC: 
    usage: /<command> [create|removeall|next|set|remove|add|delete|over|info|stats|setscore|changescore|resetscore] [Player]
    description: Commands for the Ammunition Conundrum Game
    aliases: [AmmunitionConundrum]
  delmobs:
    usage: /<command>
    description: Kills all living entities in all worlds except players. Warning! Resource-heavy and cannot be undone.
    aliases: [killmobs, deletemobs]
  delitems:
    usage: /<command>
    description: Deletes all the dropped items in all worlds. Warning! Resource-heavy and cannot be undone.
    aliases: [deleteitems]
  loadfile:
    usage: /<command> [name] [filename]
    description: Saves a list of spawns under name in filename
  loadspawns:
    usage: /<command> [name]
    description: Handles a list of already loaded spawns