name: MCPFun
main: me.MCPFun.main.MCPFunMain
version: 0.1
description: Implements a fun gamemode
commands:
  AC: 
    usage: /<command> [create|removeAll|next|set|remove|add|delete] [Player]
    description: Commands for the Ammunition Conundrum Game
    aliases: [AmmunitionConundrum]