name: MCPFun
main: me.MCPFun.main.MCPFunMain
version: 0.9
description: Implements a fun gamemode
commands:
  AC: 
    usage: /<command> [create|removeall|next|set|remove|add|delete|over|info|stats|setscore|changescore|resetscore|loadspawns] [Player]
    description: Commands for the Ammunition Conundrum Game
    aliases: [AmmunitionConundrum]
  delmobs:
    usage: /<command>
    description: Kills all living entities in all worlds except players. Warning! Resource-heavy and cannot be undone.
    aliases: [killmobs, deletemobs]
  delitems:
    usage: /<command>
    description: Deletes all the dropped items in all worlds. Warning! Resource-heavy and cannot be undone.
    aliases: [deleteitems]
  loadfile:
    usage: /<command> [name] [filename]
    description: Saves a list of spawns under name in filename
  loc:
    usage: /<command>
    description: Prints your current location
  hex:
    usage: /<command> [Player]
    description: Check a player for hacks
  createfile:
    usage: /<command> [name]
    description: Creates a .spawn file with name
  writefile:
    usage: /<command> [line|loc]
    description: Writes to the PrintWriter, if one exists
  closefile:
    usage: /<command>
    description: Closes the PrintWriter